import common.Input;
import common.InputLine;
import java.util.List;
import java.util.Iterator;

rule "extract_lines_iterator"
when
    Input($value: value)
then
    insert($value.lines().iterator());
end

rule "create_first_inputline"
when
    not InputLine()
    $iterator: Iterator( hasNext == true )
then
    insert(new InputLine(0, (String)$iterator.next()));
    update($iterator);
end

rule "create_other_inputlines"
when
    InputLine( $ln: lineNumber )
    not InputLine( lineNumber > $ln )
    $iterator: Iterator( hasNext == true )
then
    insert(new InputLine($ln + 1, (String)$iterator.next()));
    update($iterator);
end

rule "delete_iterator"
when
    $iterator: Iterator( hasNext == false )
then
    delete($iterator);
end
