import common.*;
import day1.*;
import java.util.List;

rule "parse_line"
when
    $input1: InputLine($ln: lineNumber, $val: value, value matches "^\\d+$")
then
    insert (new Depth($ln, Integer.parseInt($val)));
end

rule "count"
when
    $input1: Depth()
    $input2: Depth(lineNumber == $input1.lineNumber + 1, value > $input1.value)
then
    insert (new Count());
end

rule "display_count"
when
    $counts: List() from collect( Count() )
then
    System.err.println("part1="+$counts.size());
end